# Generated by Django 3.1.1 on 2020-12-01 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('school_year', models.PositiveIntegerField()),
                ('semester', models.CharField(choices=[('1st', 'First'), ('2nd', 'Second'), ('3rd', 'Third')], max_length=50)),
                ('subject_year', models.CharField(choices=[('1st', 'First'), ('2nd', 'Second'), ('3rd', 'Third')], max_length=50)),
                ('start_time', models.TimeField()),
                ('room', models.CharField(max_length=50)),
                ('unit', models.SmallIntegerField(blank=True, null=True)),
                ('prelim', models.SmallIntegerField(blank=True, null=True)),
                ('midterm', models.SmallIntegerField(blank=True, null=True)),
                ('finals', models.SmallIntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Student', 'Student'), ('Graduate', 'Graduate'), ('Professor', 'Professor')], max_length=50)),
                ('course', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ManyToManyField(to='core.Subject')),
            ],
        ),
    ]
