# Generated by Django 3.1.1 on 2020-11-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ManyToManyField(to='core.Course'),
        ),
    ]
