# Generated by Django 3.1.1 on 2020-11-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201126_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='school_year',
            field=models.PositiveIntegerField(),
        ),
    ]
