# Generated by Django 3.1.1 on 2020-11-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='finals',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='midterm',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='prelim',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='school_year',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='unit',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
